# 요청을 전달할 서버 목록을 정의하는 블록
upstream backend {
    server backend:8000;
}

server {
    listen 80;

    # WebSocket 요청은 여기서 처리
    location /ws {
        proxy_pass http://backend;
        # WebSocket 연결은 처음에 HTTP로 시작해서 프로토콜을 바꾸는 Upgrade HandShake를 한다.
        proxy_http_version 1.1;                  # HTTP/1.1로 백엔드와 통신 (Upgrade 지원. HTTP/1.0은 Upgrade 지원하지 않음)
        proxy_set_header Upgrade $http_upgrade;  # 브라우저가 보낸 Upgrade 헤더를 백엔드에 그대로 전달 (Nginx는 Upgrade 헤더를 기본적으로 넘기지 않아서 명시해줘야 함.) 
        proxy_set_header Connection "upgrade";  # 연결을 유지하면서 업그레이드하겠다는 신호
        proxy_set_header Host $host;        
        proxy_read_timeout 3600s;               # 기본값은 60초. WebSocket은 장시간 연결을 유지하므로 60초가 지나면 Nginx가 연결을 끊어버림. 1시간으로 늘려주기.
    }

    # 일반 HTTP REST API 요청은 여기서 처리
    location / {
        proxy_pass http://backend;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr; # Nginx를 거치면 백엔드 입장에서는 클라이언트 IP가 Nginx IP로 보임. 따라서 실제 브라우저 IP를 백엔드에 전달하려면 이 헤더가 필요함.
    }
}