"""inital

Revision ID: 04640950921d
Revises: cfb92d68aaa1
Create Date: 2026-07-09 06:29:34.735366

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '04640950921d'
down_revision: Union[str, None] = 'cfb92d68aaa1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('room_members', sa.Column('left_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('room_members', 'left_at')
    # ### end Alembic commands ###
