"""inital

Revision ID: 7d373f2dad0b
Revises: d3efcc058fa0
Create Date: 2026-07-27 03:23:30.057437

"""

from datetime import datetime, timezone
from typing import Sequence, Union
import uuid

from alembic import op
import sqlalchemy as sa

# revision identifiers, used by Alembic.
revision: str = "7d373f2dad0b"
down_revision: Union[str, None] = "d3efcc058fa0"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "allowed_reactions",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column("sort_order", sa.Integer(), nullable=False),
        sa.Column("is_active", sa.Boolean(), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint("emoji"),
    )
    op.create_table(
        "message_reactions",
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("user_id", sa.UUID(), nullable=False),
        sa.Column("emoji", sa.String(length=8), nullable=False),
        sa.Column("created_at", sa.DateTime(timezone=True), nullable=False),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.ForeignKeyConstraint(
            ["user_id"],
            ["users.id"],
        ),
        sa.PrimaryKeyConstraint("message_id", "user_id", "emoji"),
    )
    # ### end Alembic commands ###

    allowed_reactions_table = sa.table(
        "allowed_reactions",
        sa.column("id", sa.UUID()),
        sa.column("emoji", sa.String()),
        sa.column("sort_order", sa.Integer()),
        sa.column("is_active", sa.Boolean()),
        sa.column("created_at", sa.DateTime(timezone=True)),
    )
    now = datetime.now(timezone.utc)
    op.bulk_insert(
        allowed_reactions_table,
        [
            {"id": uuid.uuid4(), "emoji": "👍", "sort_order": 0, "is_active": True, "created_at": now},
            {"id": uuid.uuid4(), "emoji": "❤️", "sort_order": 1, "is_active": True, "created_at": now},
            {"id": uuid.uuid4(), "emoji": "😂", "sort_order": 2, "is_active": True, "created_at": now},
            {"id": uuid.uuid4(), "emoji": "😮", "sort_order": 3, "is_active": True, "created_at": now},
            {"id": uuid.uuid4(), "emoji": "😢", "sort_order": 4, "is_active": True, "created_at": now},
            {"id": uuid.uuid4(), "emoji": "🙏", "sort_order": 5, "is_active": True, "created_at": now},
        ],
    )


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_reactions")
    op.drop_table("allowed_reactions")
    # ### end Alembic commands ###
